CREATE USER IF NOT EXISTS SA SALT '0f7d070a6a5f2b60' HASH 'cd3e105f0486a1a04aa8fffd2dc2afda0bec8c1832b5b95fab0a67d088ad1e0c' ADMIN;
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;
CREATE CACHED TABLE PUBLIC.BILL(
    ID BIGINT NOT NULL,
    MODIFICATIONCOUNTER INTEGER NOT NULL,
    PAYED BOOLEAN NOT NULL,
    TIP DECIMAL(19, 2),
    TOTALAMOUNT DECIMAL(19, 2)
);
ALTER TABLE PUBLIC.BILL ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BILL;
CREATE CACHED TABLE PUBLIC.BILL_ORDERPOSITION(
    BILL_ID BIGINT NOT NULL,
    ORDERPOSITIONS_ID BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BILL_ORDERPOSITION;
CREATE CACHED TABLE PUBLIC.OFFER(
    ID BIGINT NOT NULL,
    MODIFICATIONCOUNTER INTEGER NOT NULL,
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255),
    CURRENTPRICE DECIMAL(19, 2),
    NUMBER BIGINT,
    STATE INTEGER,
    DRINK_ID BIGINT,
    MEAL_ID BIGINT,
    SIDEDISH_ID BIGINT
);
ALTER TABLE PUBLIC.OFFER ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OFFER;
CREATE CACHED TABLE PUBLIC.ORDERPOSITION(
    ID BIGINT NOT NULL,
    MODIFICATIONCOUNTER INTEGER NOT NULL,
    COMMENT VARCHAR(255),
    OFFERID BIGINT,
    OFFERNAME VARCHAR(255),
    PRICE DECIMAL(19, 2),
    STATE INTEGER,
    ORDER_ID BIGINT
);
ALTER TABLE PUBLIC.ORDERPOSITION ADD CONSTRAINT PUBLIC.CONSTRAINT_4F PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDERPOSITION;
CREATE CACHED TABLE PUBLIC.PRODUCT(
    DTYPE VARCHAR(31) NOT NULL,
    ID BIGINT NOT NULL,
    MODIFICATIONCOUNTER INTEGER NOT NULL,
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255),
    ALCOHOLIC BOOLEAN
);
ALTER TABLE PUBLIC.PRODUCT ADD CONSTRAINT PUBLIC.CONSTRAINT_18 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
CREATE CACHED TABLE PUBLIC.RESTAURANTTABLE(
    ID BIGINT NOT NULL,
    MODIFICATIONCOUNTER INTEGER NOT NULL,
    NUMBER BIGINT NOT NULL CHECK (NUMBER >= 0),
    STATE INTEGER,
    WAITERID BIGINT
);
ALTER TABLE PUBLIC.RESTAURANTTABLE ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANTTABLE;
CREATE CACHED TABLE PUBLIC.STAFFMEMBER(
    ID BIGINT NOT NULL,
    MODIFICATIONCOUNTER INTEGER NOT NULL,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    LOGIN VARCHAR(255),
    ROLE INTEGER
);
ALTER TABLE PUBLIC.STAFFMEMBER ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STAFFMEMBER;
CREATE CACHED TABLE PUBLIC.TABLEORDER(
    ID BIGINT NOT NULL,
    MODIFICATIONCOUNTER INTEGER NOT NULL,
    STATE INTEGER,
    TABLEID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.TABLEORDER ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TABLEORDER;
ALTER TABLE PUBLIC.OFFER ADD CONSTRAINT PUBLIC.UK_QQP12YR6YYTDE8M0IVJGU40TS UNIQUE(DESCRIPTION);
ALTER TABLE PUBLIC.RESTAURANTTABLE ADD CONSTRAINT PUBLIC.UK_TIX0POFQQAGPVPRDRJ9IP64HC UNIQUE(NUMBER);
ALTER TABLE PUBLIC.OFFER ADD CONSTRAINT PUBLIC.UK_1N5DJSJ5NCYDLVGEO18MXPK0I UNIQUE(NUMBER);
ALTER TABLE PUBLIC.STAFFMEMBER ADD CONSTRAINT PUBLIC.UK_NEIGQJB3PW0T00EVL2TEXH2EP UNIQUE(LOGIN);
ALTER TABLE PUBLIC.BILL_ORDERPOSITION ADD CONSTRAINT PUBLIC.FK_29WRX95GARFO73880F30WAI71 FOREIGN KEY(BILL_ID) REFERENCES PUBLIC.BILL(ID) NOCHECK;
ALTER TABLE PUBLIC.ORDERPOSITION ADD CONSTRAINT PUBLIC.FK_AHC7UKYBBL67EG872NDC2LHW3 FOREIGN KEY(ORDER_ID) REFERENCES PUBLIC.TABLEORDER(ID) NOCHECK;
ALTER TABLE PUBLIC.BILL_ORDERPOSITION ADD CONSTRAINT PUBLIC.FK_1C03HBID8J173A0MN5VO6TX53 FOREIGN KEY(ORDERPOSITIONS_ID) REFERENCES PUBLIC.ORDERPOSITION(ID) NOCHECK;
ALTER TABLE PUBLIC.OFFER ADD CONSTRAINT PUBLIC.FK_N4FG5G87MTC42MWMXK9B55TKY FOREIGN KEY(SIDEDISH_ID) REFERENCES PUBLIC.PRODUCT(ID) NOCHECK;
ALTER TABLE PUBLIC.OFFER ADD CONSTRAINT PUBLIC.FK_QSU4QS5HINUDRJJSPVPYF9S89 FOREIGN KEY(MEAL_ID) REFERENCES PUBLIC.PRODUCT(ID) NOCHECK;
ALTER TABLE PUBLIC.OFFER ADD CONSTRAINT PUBLIC.FK_RI5OIS39SLR1F71D9NIUW2F66 FOREIGN KEY(DRINK_ID) REFERENCES PUBLIC.PRODUCT(ID) NOCHECK;
