ALTER TABLE PUBLIC.ORDERPOSITION ADD
(
  COOKID BIGINT
);
ALTER TABLE PUBLIC.ORDERPOSITION ADD CONSTRAINT PUBLIC.FK_ORDPOS2COOK FOREIGN KEY(COOKID) REFERENCES PUBLIC.STAFFMEMBER(ID) NOCHECK;
INSERT INTO OFFER (id, description, state, meal_id, sidedish_id, drink_id, modificationCounter, currentprice) VALUES (6, 'Cola', 0, null, null, 10, 1, 1.20);
