// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package io.oasp.gastronomy.restaurant.staffmanagement.logic.api.to;

import io.oasp.gastronomy.restaurant.general.common.api.datatype.Role;

import java.util.Locale;

@SuppressWarnings("javadoc")
public class StaffMemberEtoBuilder extends StaffMemberEtoBuilderBase<StaffMemberEtoBuilder> {
  public static StaffMemberEtoBuilder staffMemberEto() {

    return new StaffMemberEtoBuilder();
  }

  public StaffMemberEtoBuilder() {

    super(new StaffMemberEto());
  }

  public StaffMemberEto build() {

    return getInstance();
  }
}

class StaffMemberEtoBuilderBase<GeneratorT extends StaffMemberEtoBuilderBase<GeneratorT>> {
  private StaffMemberEto instance;

  protected StaffMemberEtoBuilderBase(StaffMemberEto aInstance) {

    this.instance = aInstance;
  }

  protected StaffMemberEto getInstance() {

    return this.instance;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withName(String aValue) {

    this.instance.setName(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withFirstName(String aValue) {

    this.instance.setFirstName(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withLastName(String aValue) {

    this.instance.setLastName(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withRole(Role aValue) {

    this.instance.setRole(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withLanguage(Locale aValue) {

    this.instance.setLanguage(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withId(Long aValue) {

    this.instance.setId(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withModificationCounter(int aValue) {

    this.instance.setModificationCounter(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withRevision(Number aValue) {

    this.instance.setRevision(aValue);

    return (GeneratorT) this;
  }
}
