// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package io.oasp.gastronomy.restaurant.salesmanagement.logic.api.to;

import io.oasp.gastronomy.restaurant.salesmanagement.common.api.datatype.OrderState;

@SuppressWarnings("javadoc")
public class OrderEtoBuilder extends OrderEtoBuilderBase<OrderEtoBuilder> {
  public static OrderEtoBuilder orderEto() {

    return new OrderEtoBuilder();
  }

  public OrderEtoBuilder() {

    super(new OrderEto());
  }

  public OrderEto build() {

    return getInstance();
  }
}

class OrderEtoBuilderBase<GeneratorT extends OrderEtoBuilderBase<GeneratorT>> {
  private OrderEto instance;

  protected OrderEtoBuilderBase(OrderEto aInstance) {

    this.instance = aInstance;
  }

  protected OrderEto getInstance() {

    return this.instance;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withTableId(long aValue) {

    this.instance.setTableId(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withState(OrderState aValue) {

    this.instance.setState(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withId(Long aValue) {

    this.instance.setId(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withModificationCounter(int aValue) {

    this.instance.setModificationCounter(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withRevision(Number aValue) {

    this.instance.setRevision(aValue);

    return (GeneratorT) this;
  }
}
